// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.usfca.cs.dfs.messages;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Controller controller = 1;</code>
     */
    boolean hasController();
    /**
     * <code>.Controller controller = 1;</code>
     */
    edu.usfca.cs.dfs.messages.Messages.Controller getController();
    /**
     * <code>.Controller controller = 1;</code>
     */
    edu.usfca.cs.dfs.messages.Messages.ControllerOrBuilder getControllerOrBuilder();

    /**
     * <code>.Storage storage = 2;</code>
     */
    boolean hasStorage();
    /**
     * <code>.Storage storage = 2;</code>
     */
    edu.usfca.cs.dfs.messages.Messages.Storage getStorage();
    /**
     * <code>.Storage storage = 2;</code>
     */
    edu.usfca.cs.dfs.messages.Messages.StorageOrBuilder getStorageOrBuilder();

    public edu.usfca.cs.dfs.messages.Messages.ProtoMessage.MsgCase getMsgCase();
  }
  /**
   * <pre>
   * Storage related messages
   * </pre>
   *
   * Protobuf type {@code ProtoMessage}
   */
  public  static final class ProtoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoMessage)
      ProtoMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoMessage.newBuilder() to construct.
    private ProtoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              edu.usfca.cs.dfs.messages.Messages.Controller.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((edu.usfca.cs.dfs.messages.Messages.Controller) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.messages.Messages.Controller.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.messages.Messages.Controller) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              edu.usfca.cs.dfs.messages.Messages.Storage.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((edu.usfca.cs.dfs.messages.Messages.Storage) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.messages.Messages.Storage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.messages.Messages.Storage) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.messages.Messages.internal_static_ProtoMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.messages.Messages.internal_static_ProtoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.messages.Messages.ProtoMessage.class, edu.usfca.cs.dfs.messages.Messages.ProtoMessage.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      CONTROLLER(1),
      STORAGE(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return CONTROLLER;
          case 2: return STORAGE;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int CONTROLLER_FIELD_NUMBER = 1;
    /**
     * <code>.Controller controller = 1;</code>
     */
    public boolean hasController() {
      return msgCase_ == 1;
    }
    /**
     * <code>.Controller controller = 1;</code>
     */
    public edu.usfca.cs.dfs.messages.Messages.Controller getController() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.messages.Messages.Controller) msg_;
      }
      return edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance();
    }
    /**
     * <code>.Controller controller = 1;</code>
     */
    public edu.usfca.cs.dfs.messages.Messages.ControllerOrBuilder getControllerOrBuilder() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.messages.Messages.Controller) msg_;
      }
      return edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance();
    }

    public static final int STORAGE_FIELD_NUMBER = 2;
    /**
     * <code>.Storage storage = 2;</code>
     */
    public boolean hasStorage() {
      return msgCase_ == 2;
    }
    /**
     * <code>.Storage storage = 2;</code>
     */
    public edu.usfca.cs.dfs.messages.Messages.Storage getStorage() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.messages.Messages.Storage) msg_;
      }
      return edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance();
    }
    /**
     * <code>.Storage storage = 2;</code>
     */
    public edu.usfca.cs.dfs.messages.Messages.StorageOrBuilder getStorageOrBuilder() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.messages.Messages.Storage) msg_;
      }
      return edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (edu.usfca.cs.dfs.messages.Messages.Controller) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (edu.usfca.cs.dfs.messages.Messages.Storage) msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (edu.usfca.cs.dfs.messages.Messages.Controller) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (edu.usfca.cs.dfs.messages.Messages.Storage) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.messages.Messages.ProtoMessage)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.messages.Messages.ProtoMessage other = (edu.usfca.cs.dfs.messages.Messages.ProtoMessage) obj;

      if (!getMsgCase().equals(other.getMsgCase())) return false;
      switch (msgCase_) {
        case 1:
          if (!getController()
              .equals(other.getController())) return false;
          break;
        case 2:
          if (!getStorage()
              .equals(other.getStorage())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + CONTROLLER_FIELD_NUMBER;
          hash = (53 * hash) + getController().hashCode();
          break;
        case 2:
          hash = (37 * hash) + STORAGE_FIELD_NUMBER;
          hash = (53 * hash) + getStorage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.messages.Messages.ProtoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Storage related messages
     * </pre>
     *
     * Protobuf type {@code ProtoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoMessage)
        edu.usfca.cs.dfs.messages.Messages.ProtoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_ProtoMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_ProtoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.messages.Messages.ProtoMessage.class, edu.usfca.cs.dfs.messages.Messages.ProtoMessage.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.messages.Messages.ProtoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_ProtoMessage_descriptor;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.ProtoMessage getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.messages.Messages.ProtoMessage.getDefaultInstance();
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.ProtoMessage build() {
        edu.usfca.cs.dfs.messages.Messages.ProtoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.ProtoMessage buildPartial() {
        edu.usfca.cs.dfs.messages.Messages.ProtoMessage result = new edu.usfca.cs.dfs.messages.Messages.ProtoMessage(this);
        if (msgCase_ == 1) {
          if (controllerBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = controllerBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (storageBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = storageBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.messages.Messages.ProtoMessage) {
          return mergeFrom((edu.usfca.cs.dfs.messages.Messages.ProtoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.messages.Messages.ProtoMessage other) {
        if (other == edu.usfca.cs.dfs.messages.Messages.ProtoMessage.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case CONTROLLER: {
            mergeController(other.getController());
            break;
          }
          case STORAGE: {
            mergeStorage(other.getStorage());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.messages.Messages.ProtoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.messages.Messages.ProtoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.messages.Messages.Controller, edu.usfca.cs.dfs.messages.Messages.Controller.Builder, edu.usfca.cs.dfs.messages.Messages.ControllerOrBuilder> controllerBuilder_;
      /**
       * <code>.Controller controller = 1;</code>
       */
      public boolean hasController() {
        return msgCase_ == 1;
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      public edu.usfca.cs.dfs.messages.Messages.Controller getController() {
        if (controllerBuilder_ == null) {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.messages.Messages.Controller) msg_;
          }
          return edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return controllerBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance();
        }
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      public Builder setController(edu.usfca.cs.dfs.messages.Messages.Controller value) {
        if (controllerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          controllerBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      public Builder setController(
          edu.usfca.cs.dfs.messages.Messages.Controller.Builder builderForValue) {
        if (controllerBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          controllerBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      public Builder mergeController(edu.usfca.cs.dfs.messages.Messages.Controller value) {
        if (controllerBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.messages.Messages.Controller.newBuilder((edu.usfca.cs.dfs.messages.Messages.Controller) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            controllerBuilder_.mergeFrom(value);
          }
          controllerBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      public Builder clearController() {
        if (controllerBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          controllerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      public edu.usfca.cs.dfs.messages.Messages.Controller.Builder getControllerBuilder() {
        return getControllerFieldBuilder().getBuilder();
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      public edu.usfca.cs.dfs.messages.Messages.ControllerOrBuilder getControllerOrBuilder() {
        if ((msgCase_ == 1) && (controllerBuilder_ != null)) {
          return controllerBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.messages.Messages.Controller) msg_;
          }
          return edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance();
        }
      }
      /**
       * <code>.Controller controller = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.messages.Messages.Controller, edu.usfca.cs.dfs.messages.Messages.Controller.Builder, edu.usfca.cs.dfs.messages.Messages.ControllerOrBuilder> 
          getControllerFieldBuilder() {
        if (controllerBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance();
          }
          controllerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.messages.Messages.Controller, edu.usfca.cs.dfs.messages.Messages.Controller.Builder, edu.usfca.cs.dfs.messages.Messages.ControllerOrBuilder>(
                  (edu.usfca.cs.dfs.messages.Messages.Controller) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return controllerBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.messages.Messages.Storage, edu.usfca.cs.dfs.messages.Messages.Storage.Builder, edu.usfca.cs.dfs.messages.Messages.StorageOrBuilder> storageBuilder_;
      /**
       * <code>.Storage storage = 2;</code>
       */
      public boolean hasStorage() {
        return msgCase_ == 2;
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      public edu.usfca.cs.dfs.messages.Messages.Storage getStorage() {
        if (storageBuilder_ == null) {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.messages.Messages.Storage) msg_;
          }
          return edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return storageBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance();
        }
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      public Builder setStorage(edu.usfca.cs.dfs.messages.Messages.Storage value) {
        if (storageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          storageBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      public Builder setStorage(
          edu.usfca.cs.dfs.messages.Messages.Storage.Builder builderForValue) {
        if (storageBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          storageBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      public Builder mergeStorage(edu.usfca.cs.dfs.messages.Messages.Storage value) {
        if (storageBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.messages.Messages.Storage.newBuilder((edu.usfca.cs.dfs.messages.Messages.Storage) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            storageBuilder_.mergeFrom(value);
          }
          storageBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      public Builder clearStorage() {
        if (storageBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          storageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      public edu.usfca.cs.dfs.messages.Messages.Storage.Builder getStorageBuilder() {
        return getStorageFieldBuilder().getBuilder();
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      public edu.usfca.cs.dfs.messages.Messages.StorageOrBuilder getStorageOrBuilder() {
        if ((msgCase_ == 2) && (storageBuilder_ != null)) {
          return storageBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.messages.Messages.Storage) msg_;
          }
          return edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance();
        }
      }
      /**
       * <code>.Storage storage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.messages.Messages.Storage, edu.usfca.cs.dfs.messages.Messages.Storage.Builder, edu.usfca.cs.dfs.messages.Messages.StorageOrBuilder> 
          getStorageFieldBuilder() {
        if (storageBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance();
          }
          storageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.messages.Messages.Storage, edu.usfca.cs.dfs.messages.Messages.Storage.Builder, edu.usfca.cs.dfs.messages.Messages.StorageOrBuilder>(
                  (edu.usfca.cs.dfs.messages.Messages.Storage) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return storageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtoMessage)
    }

    // @@protoc_insertion_point(class_scope:ProtoMessage)
    private static final edu.usfca.cs.dfs.messages.Messages.ProtoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.messages.Messages.ProtoMessage();
    }

    public static edu.usfca.cs.dfs.messages.Messages.ProtoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtoMessage>() {
      @java.lang.Override
      public ProtoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.usfca.cs.dfs.messages.Messages.ProtoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControllerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Controller)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string controllerMessage = 1;</code>
     */
    java.lang.String getControllerMessage();
    /**
     * <code>string controllerMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getControllerMessageBytes();
  }
  /**
   * Protobuf type {@code Controller}
   */
  public  static final class Controller extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Controller)
      ControllerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Controller.newBuilder() to construct.
    private Controller(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Controller() {
      controllerMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Controller();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Controller(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              controllerMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.messages.Messages.internal_static_Controller_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.messages.Messages.internal_static_Controller_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.messages.Messages.Controller.class, edu.usfca.cs.dfs.messages.Messages.Controller.Builder.class);
    }

    public static final int CONTROLLERMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object controllerMessage_;
    /**
     * <code>string controllerMessage = 1;</code>
     */
    public java.lang.String getControllerMessage() {
      java.lang.Object ref = controllerMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        controllerMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string controllerMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getControllerMessageBytes() {
      java.lang.Object ref = controllerMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        controllerMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getControllerMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, controllerMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getControllerMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, controllerMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.messages.Messages.Controller)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.messages.Messages.Controller other = (edu.usfca.cs.dfs.messages.Messages.Controller) obj;

      if (!getControllerMessage()
          .equals(other.getControllerMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTROLLERMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getControllerMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Controller parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.messages.Messages.Controller prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Controller}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Controller)
        edu.usfca.cs.dfs.messages.Messages.ControllerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_Controller_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_Controller_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.messages.Messages.Controller.class, edu.usfca.cs.dfs.messages.Messages.Controller.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.messages.Messages.Controller.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        controllerMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_Controller_descriptor;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.Controller getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance();
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.Controller build() {
        edu.usfca.cs.dfs.messages.Messages.Controller result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.Controller buildPartial() {
        edu.usfca.cs.dfs.messages.Messages.Controller result = new edu.usfca.cs.dfs.messages.Messages.Controller(this);
        result.controllerMessage_ = controllerMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.messages.Messages.Controller) {
          return mergeFrom((edu.usfca.cs.dfs.messages.Messages.Controller)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.messages.Messages.Controller other) {
        if (other == edu.usfca.cs.dfs.messages.Messages.Controller.getDefaultInstance()) return this;
        if (!other.getControllerMessage().isEmpty()) {
          controllerMessage_ = other.controllerMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.messages.Messages.Controller parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.messages.Messages.Controller) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object controllerMessage_ = "";
      /**
       * <code>string controllerMessage = 1;</code>
       */
      public java.lang.String getControllerMessage() {
        java.lang.Object ref = controllerMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          controllerMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string controllerMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getControllerMessageBytes() {
        java.lang.Object ref = controllerMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          controllerMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string controllerMessage = 1;</code>
       */
      public Builder setControllerMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        controllerMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string controllerMessage = 1;</code>
       */
      public Builder clearControllerMessage() {
        
        controllerMessage_ = getDefaultInstance().getControllerMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string controllerMessage = 1;</code>
       */
      public Builder setControllerMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        controllerMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Controller)
    }

    // @@protoc_insertion_point(class_scope:Controller)
    private static final edu.usfca.cs.dfs.messages.Messages.Controller DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.messages.Messages.Controller();
    }

    public static edu.usfca.cs.dfs.messages.Messages.Controller getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Controller>
        PARSER = new com.google.protobuf.AbstractParser<Controller>() {
      @java.lang.Override
      public Controller parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Controller(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Controller> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Controller> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.usfca.cs.dfs.messages.Messages.Controller getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StorageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Storage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string storageMessage = 1;</code>
     */
    java.lang.String getStorageMessage();
    /**
     * <code>string storageMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getStorageMessageBytes();
  }
  /**
   * Protobuf type {@code Storage}
   */
  public  static final class Storage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Storage)
      StorageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Storage.newBuilder() to construct.
    private Storage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Storage() {
      storageMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Storage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Storage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              storageMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.messages.Messages.internal_static_Storage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.messages.Messages.internal_static_Storage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.messages.Messages.Storage.class, edu.usfca.cs.dfs.messages.Messages.Storage.Builder.class);
    }

    public static final int STORAGEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object storageMessage_;
    /**
     * <code>string storageMessage = 1;</code>
     */
    public java.lang.String getStorageMessage() {
      java.lang.Object ref = storageMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        storageMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string storageMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStorageMessageBytes() {
      java.lang.Object ref = storageMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storageMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStorageMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, storageMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStorageMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, storageMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.messages.Messages.Storage)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.messages.Messages.Storage other = (edu.usfca.cs.dfs.messages.Messages.Storage) obj;

      if (!getStorageMessage()
          .equals(other.getStorageMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STORAGEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStorageMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.messages.Messages.Storage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.messages.Messages.Storage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Storage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Storage)
        edu.usfca.cs.dfs.messages.Messages.StorageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_Storage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_Storage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.messages.Messages.Storage.class, edu.usfca.cs.dfs.messages.Messages.Storage.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.messages.Messages.Storage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        storageMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.messages.Messages.internal_static_Storage_descriptor;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.Storage getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance();
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.Storage build() {
        edu.usfca.cs.dfs.messages.Messages.Storage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.messages.Messages.Storage buildPartial() {
        edu.usfca.cs.dfs.messages.Messages.Storage result = new edu.usfca.cs.dfs.messages.Messages.Storage(this);
        result.storageMessage_ = storageMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.messages.Messages.Storage) {
          return mergeFrom((edu.usfca.cs.dfs.messages.Messages.Storage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.messages.Messages.Storage other) {
        if (other == edu.usfca.cs.dfs.messages.Messages.Storage.getDefaultInstance()) return this;
        if (!other.getStorageMessage().isEmpty()) {
          storageMessage_ = other.storageMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.messages.Messages.Storage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.messages.Messages.Storage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object storageMessage_ = "";
      /**
       * <code>string storageMessage = 1;</code>
       */
      public java.lang.String getStorageMessage() {
        java.lang.Object ref = storageMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          storageMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string storageMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStorageMessageBytes() {
        java.lang.Object ref = storageMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          storageMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string storageMessage = 1;</code>
       */
      public Builder setStorageMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        storageMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string storageMessage = 1;</code>
       */
      public Builder clearStorageMessage() {
        
        storageMessage_ = getDefaultInstance().getStorageMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string storageMessage = 1;</code>
       */
      public Builder setStorageMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        storageMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Storage)
    }

    // @@protoc_insertion_point(class_scope:Storage)
    private static final edu.usfca.cs.dfs.messages.Messages.Storage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.messages.Messages.Storage();
    }

    public static edu.usfca.cs.dfs.messages.Messages.Storage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Storage>
        PARSER = new com.google.protobuf.AbstractParser<Storage>() {
      @java.lang.Override
      public Storage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Storage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Storage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Storage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.usfca.cs.dfs.messages.Messages.Storage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Controller_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Controller_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\"U\n\014ProtoMessage\022!\n\ncont" +
      "roller\030\001 \001(\0132\013.ControllerH\000\022\033\n\007storage\030\002" +
      " \001(\0132\010.StorageH\000B\005\n\003msg\"\'\n\nController\022\031\n" +
      "\021controllerMessage\030\001 \001(\t\"!\n\007Storage\022\026\n\016s" +
      "torageMessage\030\001 \001(\tB\033\n\031edu.usfca.cs.dfs." +
      "messagesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_descriptor,
        new java.lang.String[] { "Controller", "Storage", "Msg", });
    internal_static_Controller_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Controller_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Controller_descriptor,
        new java.lang.String[] { "ControllerMessage", });
    internal_static_Storage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Storage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_descriptor,
        new java.lang.String[] { "StorageMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
